name: Hybrid Config Analysis

on:
  pull_request:
    branches:
      - "main"

jobs:
  analyze-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Istio Configs
        id: tca
        uses: tetratelabs/tca-action@main
        env:
          RUNNER_DEBUG: "1"
        with:
          tis-password: ${{ secrets.TIS_PASSWORD }}
          # mesh-config: "./configs/manifests.yaml ./configs/failed.yaml" # Multiple files with space separator
          # OR use newline separator
          local-only: true
          mesh-config: |-
            ./configs/failed.yaml
            ./configs/manifests.yaml
          # kube-config: ${{ secrets.KUBECONFIG }}
      
      - name: test
        env:
          TIS_PASS: ${{ secrets.TIS_PASSWORD }}
        run: |
          tca analyze --local-only --output-disabled-hyperlink=true -f /home/runner/work/tca-demo/tca-demo/./configs/failed.yaml -f /home/runner/work/tca-demo/tca-demo/./configs/manifests.yaml

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: ${{ steps.tca.outputs.result-file }}

      - name: Optionally Fail if there are errors
        run: |
          if [ ${{ env.error-count }} -gt 0 ]; then
            exit 1
          fi
